import type { Metadata } from 'next';
import NavbarWrapper from '@/components/NavbarWrapper';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Disclaimer – DataVisualizer',
    description: 'DataVisualizer disclaimer. Chart outputs are for informational purposes. Always verify data with original source files.',
};

export default function DisclaimerPage() {
    return (
        <div style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>
            <NavbarWrapper />
            <div className="container" style={{ maxWidth: 760, padding: '64px 24px' }}>
                <article className="prose">
                    <div style={{ marginBottom: 40 }}>
                        <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#60a5fa', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Legal</span>
                        <h1 style={{ marginTop: 8 }}>Disclaimer</h1>
                        <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>Last updated: March 2026</p>
                    </div>

                    <h2>General Disclaimer</h2>
                    <p>
                        The information and visualizations generated by DataVisualizer are intended for <strong>informational and exploratory purposes only</strong>. While we strive for accuracy in our parsing and rendering algorithms, DataVisualizer does not guarantee that the charts, extracted tables, or data interpretations are free from errors.
                    </p>

                    <h2>Data Accuracy</h2>
                    <p>
                        DataVisualizer reads and displays data exactly as it exists in your uploaded files. Chart outputs are only as accurate as the source data you provide. We are not responsible for:
                    </p>
                    <ul>
                        <li>Inaccuracies or typos in your source data.</li>
                        <li>Incorrect column type detection due to ambiguous data formatting.</li>
                        <li>Incomplete table extraction from PDF files with complex layouts or scanned images.</li>
                        <li>Missing data that arises from encoding issues in CSV or Excel files.</li>
                    </ul>

                    <h2>Not Financial, Legal, or Professional Advice</h2>
                    <p>
                        Charts and data visualizations produced by DataVisualizer should not be used as the sole basis for any financial, medical, legal, or other professional decisions. Always verify important analysis with qualified professionals and original source documents.
                    </p>

                    <h2>PDF Table Extraction Limitations</h2>
                    <p>
                        Our PDF table extraction engine uses heuristic text-position analysis. It may not correctly identify tables in all PDF layouts, particularly those created from scanned images (which lack machine-readable text), complex multi-column reports, or PDFs with heavily formatted designs. In such cases, we display a PDF preview mode as a fallback. Users should verify extracted data against the original PDF.
                    </p>

                    <h2>Third-Party Links</h2>
                    <p>
                        DataVisualizer may contain links to external websites. We are not responsible for the content, privacy practices, or accuracy of information on third-party websites. The inclusion of a link does not imply endorsement.
                    </p>

                    <h2>No Warranties</h2>
                    <p>
                        This service is provided on an "as is" basis. We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the service or any information produced by it.
                    </p>

                    <h2>Changes to the Service</h2>
                    <p>
                        DataVisualizer may update or change the service at any time. Features may be added, modified, or removed. We are not liable for any loss resulting from changes to the service.
                    </p>

                    <h2>Contact</h2>
                    <p>If you have questions about this Disclaimer, please <a href="/contact">contact us</a>.</p>
                </article>
            </div>
            <Footer />
        </div>
    );
}
