export interface ToolDef {
    slug: string;
    name: string;
    description: string;
    category:
        | 'Image Tools'
        | 'PDF Tools'
        | 'Text Tools'
        | 'Developer Tools'
        | 'Utility Tools'
        | 'Student Tools'
        | 'Business Tools'
        | 'Food Technology'
        | 'Shareable Tools';
    icon: string;
    badge: 'NEW' | 'POPULAR' | 'FREE';
    isFeatured?: boolean;
    isPopular?: boolean;
}

export const QUICK_TOOLS: ToolDef[] = [
    // Image Tools
    {
        slug: 'jpg-to-png',
        name: 'JPG to PNG Converter',
        description: 'Convert JPG/JPEG images to PNG format instantly inside your browser.',
        category: 'Image Tools',
        icon: 'Image',
        badge: 'FREE',
    },
    {
        slug: 'png-to-jpg',
        name: 'PNG to JPG Converter',
        description: 'Convert PNG images to JPG format with a white background locally.',
        category: 'Image Tools',
        icon: 'Image',
        badge: 'FREE',
    },
    {
        slug: 'webp-to-png',
        name: 'WEBP to PNG Converter',
        description: 'Convert modern WEBP files to high-quality PNG format offline.',
        category: 'Image Tools',
        icon: 'Image',
        badge: 'NEW',
    },
    {
        slug: 'png-to-webp',
        name: 'PNG to WEBP Converter',
        description: 'Convert PNG files to optimized, web-ready WEBP format.',
        category: 'Image Tools',
        icon: 'Image',
        badge: 'NEW',
    },
    {
        slug: 'image-compressor',
        name: 'Image Compressor',
        description: 'Compress image files to reduce file size with real-time quality controls.',
        category: 'Image Tools',
        icon: 'FileImage',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'image-resizer',
        name: 'Image Resizer',
        description: 'Resize images to custom width and height in pixels easily.',
        category: 'Image Tools',
        icon: 'Maximize',
        badge: 'FREE',
    },
    {
        slug: 'image-cropper',
        name: 'Image Cropper',
        description: 'Crop images visually to focus on selected sections.',
        category: 'Image Tools',
        icon: 'Crop',
        badge: 'FREE',
    },
    {
        slug: 'image-rotator',
        name: 'Image Rotator',
        description: 'Rotate images 90° CW/CCW, or flip horizontally/vertically.',
        category: 'Image Tools',
        icon: 'RotateCw',
        badge: 'FREE',
    },
    {
        slug: 'image-flipper',
        name: 'Image Flipper',
        description: 'Flip images horizontally or vertically in-browser instantly.',
        category: 'Image Tools',
        icon: 'RotateCw',
        badge: 'NEW',
    },
    {
        slug: 'image-watermark',
        name: 'Image Watermark Generator',
        description: 'Add text watermarks to your photos with custom positioning and opacity.',
        category: 'Image Tools',
        icon: 'Type',
        badge: 'NEW',
    },
    {
        slug: 'blur-image',
        name: 'Blur Image Tool',
        description: 'Apply soft blur filters to images locally in your browser sandbox.',
        category: 'Image Tools',
        icon: 'Eye',
        badge: 'FREE',
    },
    {
        slug: 'sharpen-image',
        name: 'Sharpen Image Tool',
        description: 'Increase image edge sharpness and clarity using local canvas filter matrix.',
        category: 'Image Tools',
        icon: 'Sparkles',
        badge: 'FREE',
    },
    {
        slug: 'image-metadata-viewer',
        name: 'Image Metadata Viewer',
        description: 'Read EXIF tags, camera settings, dimensions, and compression file details.',
        category: 'Image Tools',
        icon: 'Info',
        badge: 'NEW',
    },
    {
        slug: 'remove-image-metadata',
        name: 'Strip Image Metadata',
        description: 'Remove EXIF data and geolocation tags from images to protect privacy.',
        category: 'Image Tools',
        icon: 'ShieldCheck',
        badge: 'NEW',
    },
    {
        slug: 'gif-splitter',
        name: 'GIF Splitter',
        description: 'Extract individual frames from animated GIF files locally.',
        category: 'Image Tools',
        icon: 'Scissors',
        badge: 'NEW',
    },
    {
        slug: 'gif-frame-extractor',
        name: 'GIF Frame Extractor',
        description: 'Select and download specific frames from GIF images in high quality.',
        category: 'Image Tools',
        icon: 'Image',
        badge: 'FREE',
    },
    {
        slug: 'image-grid-maker',
        name: 'Image Grid Maker',
        description: 'Arrange multiple images into balanced grid cells automatically.',
        category: 'Image Tools',
        icon: 'Grid',
        badge: 'FREE',
    },
    {
        slug: 'collage-maker',
        name: 'Collage Creator',
        description: 'Stitch photos side-by-side or compile complex templates offline.',
        category: 'Image Tools',
        icon: 'Layout',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'passport-photo-maker',
        name: 'Passport Photo Maker',
        description: 'Crop and resize images to standard passport photo dimensions with guides.',
        category: 'Image Tools',
        icon: 'UserSquare',
        badge: 'NEW',
    },
    {
        slug: 'screenshot-beautifier',
        name: 'Screenshot Beautifier',
        description: 'Wrap your screenshots in premium gradient frames, shadows, and borders.',
        category: 'Image Tools',
        icon: 'Laptop',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'favicon-generator',
        name: 'Favicon Generator',
        description: 'Create multi-size favicons and web icons from any image upload.',
        category: 'Image Tools',
        icon: 'Globe',
        badge: 'FREE',
    },
    {
        slug: 'color-palette-extractor',
        name: 'Color Palette Extractor',
        description: 'Upload an image and instantly extract the dominant hex color palette.',
        category: 'Image Tools',
        icon: 'Palette',
        badge: 'NEW',
    },

    // PDF Tools
    {
        slug: 'image-to-pdf',
        name: 'Image to PDF Converter',
        description: 'Compile multiple images into a clean PDF document client-side.',
        category: 'PDF Tools',
        icon: 'FileText',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'pdf-to-image',
        name: 'PDF to Image Converter',
        description: 'Extract pages of a PDF document as high-resolution PNG images.',
        category: 'PDF Tools',
        icon: 'Image',
        badge: 'NEW',
    },
    {
        slug: 'pdf-merger',
        name: 'PDF Merger',
        description: 'Merge multiple PDF documents into a single PDF file instantly.',
        category: 'PDF Tools',
        icon: 'Files',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'pdf-splitter',
        name: 'PDF Splitter',
        description: 'Split specific page ranges of a PDF file into a new document.',
        category: 'PDF Tools',
        icon: 'Scissors',
        badge: 'FREE',
    },
    {
        slug: 'rotate-pdf',
        name: 'Rotate PDF Pages',
        description: 'Rotate individual pages inside a PDF file and save the rotated output.',
        category: 'PDF Tools',
        icon: 'RotateCw',
        badge: 'FREE',
    },
    {
        slug: 'compress-pdf',
        name: 'PDF Compressor',
        description: 'Reduce PDF file size by compressing internal embedded image assets.',
        category: 'PDF Tools',
        icon: 'FileText',
        badge: 'NEW',
    },
    {
        slug: 'extract-pdf-pages',
        name: 'Extract PDF Pages',
        description: 'Extract specific pages from a PDF document into a new standalone file.',
        category: 'PDF Tools',
        icon: 'FileText',
        badge: 'NEW',
    },
    {
        slug: 'delete-pdf-pages',
        name: 'Delete PDF Pages',
        description: 'Remove unwanted pages from your PDF file and download the cleaned version.',
        category: 'PDF Tools',
        icon: 'Trash2',
        badge: 'FREE',
    },
    {
        slug: 'rearrange-pdf-pages',
        name: 'Rearrange PDF Pages',
        description: 'Drag and drop PDF page slides to reorder pages visually.',
        category: 'PDF Tools',
        icon: 'Grid',
        badge: 'NEW',
    },
    {
        slug: 'pdf-page-numbering',
        name: 'PDF Page Numberer',
        description: 'Add page numbers at the bottom right or center coordinates of your PDF pages.',
        category: 'PDF Tools',
        icon: 'Hash',
        badge: 'FREE',
    },
    {
        slug: 'pdf-metadata-viewer',
        name: 'PDF Metadata Editor',
        description: 'Read and edit PDF meta tags: Title, Author, Subject, and Keywords.',
        category: 'PDF Tools',
        icon: 'Info',
        badge: 'NEW',
    },
    {
        slug: 'unlock-pdf',
        name: 'Unlock Protected PDF',
        description: 'Decrypt password-locked PDF files locally using your known credentials.',
        category: 'PDF Tools',
        icon: 'Unlock',
        badge: 'NEW',
    },
    {
        slug: 'protect-pdf',
        name: 'Encrypt & Protect PDF',
        description: 'Add owner passwords and restrict editing/copying on PDF documents.',
        category: 'PDF Tools',
        icon: 'Lock',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'pdf-preview',
        name: 'PDF Preview',
        description: 'Preview and navigate PDF pages with fit-width and zoom controls.',
        category: 'PDF Tools',
        icon: 'Eye',
        badge: 'FREE',
    },

    // Text Tools
    {
        slug: 'fancy-text-generator',
        name: 'Fancy Text Generator',
        description: 'Convert standard text into stylish, cool unicode fonts for social media bios and posts.',
        category: 'Text Tools',
        icon: 'Sparkles',
        badge: 'NEW',
    },
    {
        slug: 'hashtag-generator',
        name: 'Viral Hashtag Generator',
        description: 'Generate high-engagement, trending hashtags based on your topic keywords.',
        category: 'Text Tools',
        icon: 'Hash',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'youtube-title-generator',
        name: 'YouTube Title & Idea Generator',
        description: 'Get high-CTR, click-worthy titles for your YouTube videos using formula patterns.',
        category: 'Text Tools',
        icon: 'Youtube',
        badge: 'NEW',
    },
    {
        slug: 'word-counter',
        name: 'Word Counter',
        description: 'Get live stats on words, characters, sentences, paragraphs, and reading time.',
        category: 'Text Tools',
        icon: 'FileSpreadsheet',
        badge: 'FREE',
    },
    {
        slug: 'character-counter',
        name: 'Character Counter',
        description: 'Analyze letter frequency, character counts, and line metrics in text.',
        category: 'Text Tools',
        icon: 'Hash',
        badge: 'FREE',
    },
    {
        slug: 'remove-duplicate-lines',
        name: 'Remove Duplicate Lines',
        description: 'Strip duplicates from any list or text with optional sorting.',
        category: 'Text Tools',
        icon: 'ListFilter',
        badge: 'NEW',
    },
    {
        slug: 'password-generator',
        name: 'Password Generator',
        description: 'Create cryptographically secure passwords with custom strength settings.',
        category: 'Text Tools',
        icon: 'Key',
        badge: 'POPULAR',
        isPopular: true,
    },

    // Developer Tools
    {
        slug: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Beautify, format, parse, or minify JSON data instantly.',
        category: 'Developer Tools',
        icon: 'Code',
        badge: 'FREE',
    },
    {
        slug: 'json-viewer',
        name: 'JSON Viewer',
        description: 'Browse nested JSON data in an interactive collapsible tree view.',
        category: 'Developer Tools',
        icon: 'FolderTree',
        badge: 'NEW',
        isFeatured: true,
    },
    {
        slug: 'base64-encoder',
        name: 'Base64 Encoder',
        description: 'Encode text strings or binary files to Base64 format safely.',
        category: 'Developer Tools',
        icon: 'Binary',
        badge: 'FREE',
    },
    {
        slug: 'base64-decoder',
        name: 'Base64 Decoder',
        description: 'Decode Base64 strings back to text or download as raw binary file.',
        category: 'Developer Tools',
        icon: 'Binary',
        badge: 'FREE',
    },
    {
        slug: 'url-encoder',
        name: 'URL Encoder',
        description: 'Encode query parameters and special characters in URLs.',
        category: 'Developer Tools',
        icon: 'Globe',
        badge: 'FREE',
    },
    {
        slug: 'url-decoder',
        name: 'URL Decoder',
        description: 'Decode URL-encoded parameters back to standard text.',
        category: 'Developer Tools',
        icon: 'Globe',
        badge: 'FREE',
    },
    {
        slug: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate standard v1 and v4 UUID tokens in bulk.',
        category: 'Developer Tools',
        icon: 'Key',
        badge: 'NEW',
    },
    {
        slug: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode JWT headers and payloads client-side with signature status.',
        category: 'Developer Tools',
        icon: 'ShieldAlert',
        badge: 'NEW',
    },
    {
        slug: 'json-validator',
        name: 'JSON Validator & Linter',
        description: 'Validate and check JSON syntax with precise line error indicators.',
        category: 'Developer Tools',
        icon: 'CheckSquare',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'regex-tester',
        name: 'Regex Match Tester',
        description: 'Test Javascript regular expressions with live highlights and match groups.',
        category: 'Developer Tools',
        icon: 'Regex',
        badge: 'FREE',
    },
    {
        slug: 'timestamp-converter',
        name: 'Epoch Timestamp Converter',
        description: 'Convert Unix Epoch timestamps to ISO, UTC, and local time zones.',
        category: 'Developer Tools',
        icon: 'CalendarClock',
        badge: 'FREE',
    },
    {
        slug: 'html-preview',
        name: 'HTML Live Preview',
        description: 'Write HTML, CSS, and JS and preview execution instantly side-by-side.',
        category: 'Developer Tools',
        icon: 'Eye',
        badge: 'NEW',
    },
    {
        slug: 'markdown-preview',
        name: 'Markdown Live Preview',
        description: 'Format Markdown documents with real-time HTML rendering previews.',
        category: 'Developer Tools',
        icon: 'FileText',
        badge: 'FREE',
    },
    {
        slug: 'color-converter',
        name: 'HEX/RGB/HSL Color Converter',
        description: 'Convert colors between HEX, RGB, HSL, CMYK, and HSV palettes.',
        category: 'Developer Tools',
        icon: 'Palette',
        badge: 'FREE',
    },

    // Utility Tools
    {
        slug: 'age-calculator',
        name: 'Age Calculator',
        description: 'Calculate your exact age in years, months, days, and countdown to next birthday.',
        category: 'Utility Tools',
        icon: 'Calendar',
        badge: 'FREE',
    },
    {
        slug: 'bmi-calculator',
        name: 'BMI Calculator',
        description: 'Compute Body Mass Index (BMI) and discover your health category.',
        category: 'Utility Tools',
        icon: 'Activity',
        badge: 'FREE',
    },
    {
        slug: 'percentage-calculator',
        name: 'Percentage Calculator',
        description: 'Calculate percentage values, percentage ratios, and increase/decrease.',
        category: 'Utility Tools',
        icon: 'Percent',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'unit-converter',
        name: 'Unit Converter',
        description: 'Convert Length, Weight, Temperature, Area, and Volume units instantly.',
        category: 'Utility Tools',
        icon: 'RefreshCw',
        badge: 'FREE',
    },

    // Student Tools
    {
        slug: 'attendance-calculator',
        name: 'Attendance Calculator',
        description: 'Calculate how many classes you can skip or need to attend to hit your attendance goal.',
        category: 'Student Tools',
        icon: 'CalendarCheck',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'cgpa-calculator',
        name: 'CGPA Calculator',
        description: 'Track and calculate your cumulative GPA across multiple semesters.',
        category: 'Student Tools',
        icon: 'GraduationCap',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'gpa-converter',
        name: 'GPA Converter',
        description: 'Convert GPA grades between 4.0 scale, 10.0 scale, and percentage values.',
        category: 'Student Tools',
        icon: 'Percent',
        badge: 'FREE',
    },
    {
        slug: 'study-timer',
        name: 'Study Timer & Stopwatch',
        description: 'Customizable countdown timers and stopwatch to focus on your studies.',
        category: 'Student Tools',
        icon: 'Clock',
        badge: 'FREE',
    },
    {
        slug: 'pomodoro-timer',
        name: 'Pomodoro Timer',
        description: 'Enhance your study productivity with customizable 25/5 intervals and audio alarms.',
        category: 'Student Tools',
        icon: 'Timer',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'exam-countdown',
        name: 'Exam Countdown Timer',
        description: 'Set custom countdown timers for upcoming exam dates and deadlines.',
        category: 'Student Tools',
        icon: 'Hourglass',
        badge: 'NEW',
    },
    {
        slug: 'resume-builder',
        name: 'Professional Resume Builder',
        description: 'Create a professional resume in minutes and export directly to print-ready PDF.',
        category: 'Student Tools',
        icon: 'FileUser',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'internship-resume-builder',
        name: 'Internship Resume Builder',
        description: 'Specifically tailored resume builder for students applying to internships.',
        category: 'Student Tools',
        icon: 'Briefcase',
        badge: 'NEW',
    },
    {
        slug: 'cover-page-generator',
        name: 'Academic Cover Page Generator',
        description: 'Design beautiful assignment front sheets and cover pages in standard formats.',
        category: 'Student Tools',
        icon: 'FileText',
        badge: 'FREE',
    },

    // Business Tools
    {
        slug: 'gst-calculator',
        name: 'GST Calculator India',
        description: 'Calculate Central GST (CGST), State GST (SGST), and Integrated GST (IGST) splits online.',
        category: 'Business Tools',
        icon: 'Percent',
        badge: 'FREE',
    },
    {
        slug: 'emi-calculator',
        name: 'Home & Car Loan EMI Calculator',
        description: 'Calculate monthly loan EMI payments, total interest payable, and amortization schedules.',
        category: 'Business Tools',
        icon: 'DollarSign',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'sip-calculator',
        name: 'SIP Investment Mutual Fund Calculator',
        description: 'Calculate future wealth estimates for your monthly systematic investment plans (SIP).',
        category: 'Business Tools',
        icon: 'TrendingUp',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'income-tax-calculator',
        name: 'Income Tax Calculator India (FY 2025-26)',
        description: 'Calculate net tax liability under the new tax regime and compare tax splits.',
        category: 'Business Tools',
        icon: 'Calculator',
        badge: 'NEW',
    },
    {
        slug: 'fd-calculator',
        name: 'Fixed Deposit (FD) Calculator',
        description: 'Calculate FD maturity amounts, compounding returns, and interest payouts.',
        category: 'Business Tools',
        icon: 'CircleDot',
        badge: 'FREE',
    },
    {
        slug: 'ppf-calculator',
        name: 'Public Provident Fund (PPF) Calculator',
        description: 'Calculate PPF maturity values, yearly interest accruals, and investment returns.',
        category: 'Business Tools',
        icon: 'Briefcase',
        badge: 'FREE',
    },
    {
        slug: 'invoice-generator',
        name: 'PDF Invoice Generator',
        description: 'Generate professional business invoices with custom items, taxes, and download PDF.',
        category: 'Business Tools',
        icon: 'Receipt',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'quotation-generator',
        name: 'Quotation Creator',
        description: 'Generate product quotes and estimates for your clients instantly in PDF format.',
        category: 'Business Tools',
        icon: 'FileSpreadsheet',
        badge: 'NEW',
    },
    {
        slug: 'business-card-generator',
        name: 'Business Card Designer',
        description: 'Create a professional business card with custom colors, contact details, and logo.',
        category: 'Business Tools',
        icon: 'Contact',
        badge: 'NEW',
    },
    {
        slug: 'letterhead-generator',
        name: 'Company Letterhead Generator',
        description: 'Design and draft official business letters with professional headers and footers.',
        category: 'Business Tools',
        icon: 'FileSignature',
        badge: 'FREE',
    },
    {
        slug: 'signature-generator',
        name: 'E-Signature Generator',
        description: 'Draw or type online signatures and export as transparent PNG files.',
        category: 'Business Tools',
        icon: 'PenTool',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'certificate-generator',
        name: 'Certificate Maker',
        description: 'Generate customized participation or excellence awards with printable templates.',
        category: 'Business Tools',
        icon: 'Award',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'receipt-generator',
        name: 'Receipt Generator',
        description: 'Draft and compile professional print-ready receipt details for business sales.',
        category: 'Business Tools',
        icon: 'Receipt',
        badge: 'NEW',
    },

    // Food Technology
    {
        slug: 'milk-snf-calculator',
        name: 'Milk SNF Calculator',
        description: 'Calculate Solids-Not-Fat (SNF) in milk using Lactometer Reading (CLR) and Gerber Fat.',
        category: 'Food Technology',
        icon: 'Droplet',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'gerber-fat-calculator',
        name: 'Gerber Fat Calculator',
        description: 'Analyze milk fat percentages and adjust standard ratios for processing.',
        category: 'Food Technology',
        icon: 'Activity',
        badge: 'FREE',
    },
    {
        slug: 'ffa-calculator',
        name: 'FFA Acidity Calculator',
        description: 'Determine Free Fatty Acids (FFA) percentage in oils via titration inputs.',
        category: 'Food Technology',
        icon: 'Flame',
        badge: 'NEW',
    },
    {
        slug: 'moisture-basis-converter',
        name: 'Moisture Basis Converter',
        description: 'Convert food moisture levels between Wet Basis (WB) and Dry Basis (DB).',
        category: 'Food Technology',
        icon: 'Thermometer',
        badge: 'FREE',
    },
    {
        slug: 'recipe-scaling-calculator',
        name: 'Recipe Scaling Calculator',
        description: 'Scale food recipe ingredient ratios up or down based on total target yield.',
        category: 'Food Technology',
        icon: 'Scale',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'food-cost-calculator',
        name: 'Food Cost & Margin Calculator',
        description: 'Calculate recipe food cost percentages, portion pricing, and profit margins.',
        category: 'Food Technology',
        icon: 'DollarSign',
        badge: 'NEW',
    },
    {
        slug: 'nutrition-label-calculator',
        name: 'FDA Nutrition Facts Panel Generator',
        description: 'Generate standard FDA nutrition facts panels based on ingredient details.',
        category: 'Food Technology',
        icon: 'Heart',
        badge: 'POPULAR',
        isFeatured: true,
        isPopular: true,
    },
    {
        slug: 'batch-yield-calculator',
        name: 'Batch Yield Calculator',
        description: 'Measure factory batch yield efficiency and raw material wastage index.',
        category: 'Food Technology',
        icon: 'Combine',
        badge: 'FREE',
    },
    {
        slug: 'shelf-life-calculator',
        name: 'Food Shelf Life Estimator',
        description: 'Estimate storage shelf-life using standard Q10 biochem values and temperatures.',
        category: 'Food Technology',
        icon: 'Calendar',
        badge: 'NEW',
    },
    {
        slug: 'haccp-decision-tree',
        name: 'HACCP Codex Decision Tree Wizard',
        description: 'Interactive Codex wizard to identify Critical Control Points (CCPs) for food safety.',
        category: 'Food Technology',
        icon: 'ShieldCheck',
        badge: 'NEW',
    },

    // Shareable Tools
    {
        slug: 'qr-generator-pro',
        name: 'QR Code Generator Pro',
        description: 'Generate custom QR codes with logo overlays, color gradients, and border frames.',
        category: 'Shareable Tools',
        icon: 'QrCode',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'barcode-generator-pro',
        name: 'EAN/UPC Barcode Generator Pro',
        description: 'Create industrial Code 128, EAN-13, and UPC barcodes with print settings.',
        category: 'Shareable Tools',
        icon: 'Barcode',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'random-team-generator',
        name: 'Random Team Generator',
        description: 'Input list of names and instantly split them into balanced random teams.',
        category: 'Shareable Tools',
        icon: 'Users',
        badge: 'FREE',
    },
    {
        slug: 'random-name-picker',
        name: 'Random Name Picker',
        description: 'Pick random winners or draw names from lists with full animations.',
        category: 'Shareable Tools',
        icon: 'UserCheck',
        badge: 'NEW',
    },
    {
        slug: 'spin-wheel',
        name: 'Interactive Decision Spin Wheel',
        description: 'Customize a prize spin wheel and draw random choices with sound effects.',
        category: 'Shareable Tools',
        icon: 'HelpCircle',
        badge: 'POPULAR',
        isPopular: true,
    },
    {
        slug: 'coin-flip',
        name: '3D Coin Flipper',
        description: 'Flip a coin with high-performance CSS 3D rotation animations.',
        category: 'Shareable Tools',
        icon: 'CircleDot',
        badge: 'FREE',
    },
    {
        slug: 'dice-roller',
        name: '3D Dice Roller',
        description: 'Roll up to 5 dice simultaneously with realistic rolling physics animations.',
        category: 'Shareable Tools',
        icon: 'Dices',
        badge: 'FREE',
    }
];

export const CATEGORIES = [
    { name: 'Image Tools', icon: '🎨', color: '#ec4899', slug: 'image' },
    { name: 'PDF Tools', icon: '📕', color: '#ef4444', slug: 'pdf' },
    { name: 'Text Tools', icon: '📝', color: '#f59e0b', slug: 'text' },
    { name: 'Developer Tools', icon: '💻', color: '#10b981', slug: 'developer' },
    { name: 'Utility Tools', icon: '🛠️', color: '#3b82f6', slug: 'utility' },
    { name: 'Student Tools', icon: '🎓', color: '#6366f1', slug: 'student' },
    { name: 'Business Tools', icon: '💼', color: '#f43f5e', slug: 'business' },
    { name: 'Food Technology', icon: '🧪', color: '#8b5cf6', slug: 'food-tech' },
    { name: 'Shareable Tools', icon: '🤝', color: '#0ea5e9', slug: 'shareable' }
];

export function getToolBySlug(slug: string): ToolDef | undefined {
    return QUICK_TOOLS.find((t) => t.slug === slug);
}

export function getRelatedTools(tool: ToolDef, limit = 3): ToolDef[] {
    return QUICK_TOOLS.filter((t) => t.slug !== tool.slug && t.category === tool.category).slice(0, limit);
}
