import type { Metadata } from 'next';
import NavbarWrapper from '@/components/NavbarWrapper';
import Footer from '@/components/Footer';
import FormulaGenerator from '@/components/dashboard/FormulaGenerator';
import DiscoveryLinks from '@/components/DiscoveryLinks';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Free Excel Formula Generator – VLOOKUP, XLOOKUP, INDEX MATCH | VisualizeMyData',
    description: 'Generate Excel and Google Sheets formulas online for free. Use our searchable helper or interactive builder to write VLOOKUP, XLOOKUP, INDEX MATCH, SUMIF, and COUNTIF formulas in seconds.',
    alternates: {
        canonical: 'https://visualizemydata.in/excel-formula-generator/',
    },
    openGraph: {
        title: 'Free Excel Formula Generator – VLOOKUP, XLOOKUP, INDEX MATCH | VisualizeMyData',
        description: 'Generate Excel and Google Sheets formulas online for free. Use our searchable helper or interactive builder to write VLOOKUP, XLOOKUP, INDEX MATCH, SUMIF, and COUNTIF formulas in seconds.',
        url: 'https://visualizemydata.in/excel-formula-generator/',
        type: 'website',
        siteName: 'VisualizeMyData',
        locale: 'en_US',
        images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'VisualizeMyData Excel Formula Generator' }],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Free Excel Formula Generator – VLOOKUP, XLOOKUP, INDEX MATCH | VisualizeMyData',
        description: 'Generate Excel and Google Sheets formulas online for free. Search or build VLOOKUP, XLOOKUP, SUMIF, and COUNTIF instantly.',
        images: ['/og-image.png'],
    },
};

const faqItems = [
    { q: 'How does the Excel formula generator work?', a: 'You can choose to search our formula catalog or use our interactive form builder. By filling in simple parameters (like lookup range, value column, or match criteria), the tool formats the syntax automatically, giving you a perfect copy-pasteable formula.' },
    { q: 'Are the formulas compatible with Google Sheets?', a: 'Yes. All formulas generated by the tool use standard spreadsheet syntax supported natively by both Microsoft Excel and Google Sheets.' },
    { q: 'What is the difference between VLOOKUP and XLOOKUP?', a: 'VLOOKUP is a legacy function that searches the first column of a table and can only return values to the right. XLOOKUP is a modern, safer replacement that can search columns to the left, supports default fallback values, and handles range changes without breaking.' },
    { q: 'Does this tool require registration?', a: 'No. The formula generator is completely open and free to use without any account registration or subscription tiers.' },
    { q: 'How do I avoid syntax errors like #REF! or #VALUE!?', a: 'The generator outputs pre-formatted formulas with exact commas, quotation marks, and parenthesis positioning. Simply copy the code block and paste it directly into your formula bar to prevent typical syntax errors.' }
];

const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqItems.map(({ q, a }) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
    })),
};

const webAppSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Free Excel Formula Generator',
    url: 'https://visualizemydata.in/excel-formula-generator/',
    description: 'Generate complex Excel and Google Sheets formulas instantly using our interactive online tool. Learn syntax, parameters, and examples.',
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'All',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    browserRequirements: 'Requires a modern web browser with JavaScript enabled.',
};

export default function Page() {
    return (
        <div style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }} />
            <NavbarWrapper />

            {/* Hero Header */}
            <section style={{ padding: '60px 0 40px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none' }}>
                    <div style={{ position: 'absolute', top: '-10%', left: '50%', transform: 'translateX(-50%)', width: 600, height: 600, background: 'radial-gradient(circle, rgba(144,147,255,0.08) 0%, transparent 70%)', borderRadius: '50%' }} />
                </div>
                <div className="container" style={{ position: 'relative', maxWidth: 720 }}>
                    <span style={{ display: 'inline-block', padding: '4px 14px', borderRadius: 99, background: 'rgba(144, 147, 255, 0.08)', border: '1px solid rgba(144, 147, 255, 0.25)', fontSize: '0.7rem', fontWeight: 700, color: '#b4c6fc', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 20 }}>
                        Formula Helper
                    </span>
                    <h1 style={{ fontFamily: 'var(--font-manrope)', fontSize: 'clamp(2rem, 5vw, 3rem)', fontWeight: 900, color: 'var(--text-primary)', lineHeight: 1.15, marginBottom: 16 }}>
                        Free Excel Formula Generator
                    </h1>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', lineHeight: 1.7, maxWidth: 560, margin: '0 auto 28px' }}>
                        Build complex spreadsheet formulas without memorizing syntax. Search our catalog or use the interactive builder to generate copyable formulas.
                    </p>
                </div>
            </section>

            {/* Main Interactive Tool Container */}
            <main className="container" style={{ paddingBottom: 80 }}>
                <FormulaGenerator />
            </main>

            {/* Informational SEO Section */}
            <section style={{ padding: '60px 0 70px', borderTop: '1px solid var(--border-subtle)', background: 'var(--bg-secondary)' }}>
                <div className="container" style={{ maxWidth: 800 }}>
                    <h2 style={{ fontFamily: 'var(--font-manrope)', color: 'var(--text-primary)', fontSize: '1.4rem', fontWeight: 800, marginBottom: 16 }}>
                        Master Spreadsheet Formulas Instantly
                    </h2>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: 1.8, marginBottom: 20 }}>
                        Modern business depends on spreadsheet calculations, but formatting parameters correctly in formulas like VLOOKUP, INDEX MATCH, or SUMIF is notoriously difficult. A single misplaced comma or mismatched range can trigger frustrating errors like #N/A, #VALUE!, or #REF!. The VisualizeMyData Excel Formula Generator removes the guesswork by showing exactly how parameters relate to your goals.
                    </p>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: 1.8, marginBottom: 20 }}>
                        By breaking down each formula component into interactive inputs, the tool lets you specify your lookup values, table arrays, and target columns without worrying about syntax symbols. The generator builds the nested formulas on the fly, explaining what each function achieves.
                    </p>

                    <h3 style={{ fontFamily: 'var(--font-manrope)', color: 'var(--text-primary)', fontSize: '1.1rem', fontWeight: 700, marginTop: 32, marginBottom: 12 }}>
                        Formulas You Can Generate:
                    </h3>
                    <ul style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', paddingLeft: 20, lineHeight: 2, marginBottom: 30 }}>
                        <li><strong>XLOOKUP:</strong> The modern way to search rows. Can look left, default fallback values, and works without column index numbers.</li>
                        <li><strong>VLOOKUP:</strong> Standard vertical lookup. Searches the leftmost column of your table and returns values to the right.</li>
                        <li><strong>INDEX MATCH:</strong> The industry standard for large spreadsheets, supporting leftward matching and dynamic columns.</li>
                        <li><strong>SUMIF:</strong> Sums range cells depending on whether they satisfy a target logical condition.</li>
                        <li><strong>COUNTIF:</strong> Scans cell columns and counts cells meeting criteria (e.g. tracking absences or passing scores).</li>
                    </ul>

                    <h3 style={{ fontFamily: 'var(--font-manrope)', color: 'var(--text-primary)', fontSize: '1.1rem', fontWeight: 700, marginBottom: 12 }}>
                        Perfect for Excel &amp; Google Sheets
                    </h3>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: 1.8, marginBottom: 24 }}>
                        All generated formulas utilize standard syntax supported by both Microsoft Excel and Google Sheets. Simply click the copy button, double-click a cell in your spreadsheet, paste the formula, and press Enter.
                    </p>

                    <h3 style={{ fontFamily: 'var(--font-manrope)', color: 'var(--text-primary)', fontSize: '1.1rem', fontWeight: 700, marginBottom: 12 }}>
                        Related Spreadsheets Tools
                    </h3>
                    <ul style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', paddingLeft: 20, lineHeight: 2 }}>
                        <li><Link href="/excel-visualizer/" style={{ color: 'var(--accent)' }}>→ <strong>Excel Data Visualizer</strong></Link> — plot interactive charts from Excel sheets</li>
                        <li><Link href="/dashboard-generator/" style={{ color: 'var(--accent)' }}>→ <strong>Interactive Dashboard Builder</strong></Link> — build full KPI layouts from custom file uploads</li>
                        <li><Link href="/data-cleaning-tool/" style={{ color: 'var(--accent)' }}>→ <strong>Online Data Cleaner</strong></Link> — prepare Excel files by removing duplicates</li>
                    </ul>
                </div>
            </section>

            {/* FAQ Accordion */}
            <section style={{ padding: '48px 0 64px', background: 'var(--bg-primary)' }}>
                <div className="container" style={{ maxWidth: 800 }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--text-primary)', marginBottom: 32 }}>Frequently Asked Questions</h2>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                        {faqItems.map(({ q, a }) => (
                            <div key={q} style={{ padding: '20px 24px', borderRadius: 12, border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }}>
                                <p style={{ fontWeight: 700, color: 'var(--text-primary)', marginBottom: 8, lineHeight: 1.5 }}>{q}</p>
                                <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>{a}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            <DiscoveryLinks />
            <Footer />
        </div>
    );
}
